apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: client-x
  labels:
    app: mariadb
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
    - name: tcp
      protocol: TCP
      port: 3306