apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: client-x
spec:
  storageClassName: "mysql-storage"
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests: 
      storage: 10Gi