version: '3.9'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'technical_test'
            MYSQL_USER: 'technical_test'
            MYSQL_PASSWORD: 'TkJuDgZLjdc2z4ff'
            MYSQL_ROOT_PASSWORD: 'Tktewfertdc2z4fd'
            MYSQL_ROOT_USER: root
        ports:
            - 3308:3306
        volumes:
            - db_data:/var/lib/mysql/

    php:
        image: iftitutul/php-app:v1.1.0
        restart: always
        volumes:
            - web_content:/var/www/vhosts/client-x

    web:
        depends_on:
            - db
            - php
        links:
            - db
            - php
        image: nginx:1.20-alpine
        restart: always
        volumes:
            - web_content:/var/www/vhosts/client-x
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

volumes:
  db_data: {}
  web_content: {}