apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: client-x
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXED: Use internal DNS name
    server: 10.104.9.29
    path: "/"